### ISSUE TITLE
Errors upon upgrading to 0.43.0

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db-test-utils#18]
Note the tests still pass

![image](https://user-images.githubusercontent.com/106148/82670834-ddeb9a80-9c0b-11ea-93c8-78b926f2b84a.png)

**Comment by achingbrain** [comment]
It’s hard to see what is causing the error as it’s being masked by the unhandled rejection, but this might be related to https://github.com/libp2p/js-libp2p-tcp/issues/130

**Comment by aphelionz** [comment]
Errors are no longer around in newer versions
