### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db-test-utils#3]
We also have https://github.com/orbitdb/orbitdb-test-utils. Are these the same?

If so, we should close one of them (given the name of the previous, I think we could delete that one?).

**Comment by aphelionz** [comment]
Hmm! I totally missed that you did that. Yours seems more mature and I think it's literally the same code - I just copied the latest utils folder from `ipfs-log,` which may have some updates.

**Comment by haadcode** [comment]
That's totally fine :) I like your repo better because it follows the naming convention of all orbitdb repos (orbit-db with a dash).

Up to you, I have no strong preference. We can keep using this repo (just make sure it's the latest code, which I believe it is if you copied it from ipfs-log/orbitdb).

**Comment by RichardLitt** [comment]
@aphelionz 	Have you closed down the other repo?

**Comment by aphelionz** [comment]
All set
