### ISSUE TITLE
What is "mongo-unit" needed for?

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db-test-utils#34]
There's the dependency `mongo-unit` in the [package.json](https://github.com/orbitdb/orbit-db-test-utils/blob/3e2977d9e7772cadcc48581d75af24a8105d03af/package.json#L31) as a devDependency.

Trying to search through the code base, I can't find it being used anywhere.

Is it used anywhere and is it still needed?

cc @aphelionz

**Comment by aphelionz** [comment]
It's cruft and can be removed. It was originally used for the storage-adapter to test leveldown compliance via `mongodown` but those tests will be moved to that repo moving forward
