### ISSUE TITLE
Remove redis-server

### ISSUE THREAD

**Issue by shamb0t** [orbitdb/orbit-db-test-utils#4]
RIght now this forces all repos using this package to download the > 8 MB file and it isn't useful to the majority of test cases. It should be downloaded separately when needed

**Comment by aphelionz** [comment]
I agree with this, and it's perhaps worse than one might think!

We currently download *three* large files that we need for testing, perhaps more:
1. redis-server (8mb)
2. chromium (112.6 mb)
3. go-ipfs (19 mb)

I'm very open to suggestions on how to mitigate this, go easier on folks with bandwidth restructions, and perhaps make builds faster.

One idea we had was to "lazy load" these dependencies when the tests are called. Not sure how involved that might be but it's something to consider. Again, very open to ideas here.
